import { useMutation, useQuery, useQueryClient } from "@tanstack/react-query";
import { BadgePercent, Building2, PlugZap, RefreshCcw, Save, Zap } from "lucide-react";
import { useState } from "react";
import { z } from "zod";
import { Button, ErrorState, LoadingState, MetricTile, PageHeader, SelectInput, TextInput } from "@skima/ui";
import { useSessionState } from "./session";

const RowSchema = z.record(z.unknown());
const SnapshotSchema = z.object({ categories:z.array(RowSchema), billers:z.array(RowSchema), products:z.array(RowSchema), routes:z.array(RowSchema), providers:z.array(RowSchema), promotions:z.array(RowSchema), payments:z.array(RowSchema) });
type Row = z.infer<typeof RowSchema>;
type SetupStep = "category" | "biller" | "product" | "connection" | "promotion";
const steps: ReadonlyArray<{ key: SetupStep; label: string; detail: string }> = [
  { key:"category", label:"Service types", detail:"Electricity, airtime, data and more" },
  { key:"biller", label:"Companies", detail:"The companies customers can pay" },
  { key:"product", label:"Plans", detail:"Amounts and customer details required" },
  { key:"connection", label:"Connections", detail:"Connect plans to an approved provider" },
  { key:"promotion", label:"Offers", detail:"Discounts and campaign limits" },
];

export function AdminUtilityBillingWorkspace() {
  const { supabase, status } = useSessionState();
  const client = useQueryClient();
  const [step,setStep] = useState<SetupStep>("category");
  const snapshot = useQuery({ queryKey:["admin-utility-billing"], enabled:status==="authenticated", queryFn:async()=>{ const {data,error}=await supabase.rpc("read_utility_admin_configuration"); if(error) throw error; return SnapshotSchema.parse(data); } });
  const save = useMutation({ mutationFn:async(input:{kind:string;key:string;configuration:Record<string,unknown>})=>{ const {error}=await supabase.rpc("configure_utility_catalog_item",{target_kind:input.kind,target_key:input.key,target_configuration:input.configuration}); if(error) throw error; }, onSuccess:async()=>client.invalidateQueries({queryKey:["admin-utility-billing"]}) });
  const connect = useMutation({ mutationFn:async(input:{productKey:string;providerKey:string;productCode:string;priority:number;state:string;fee:number})=>{ const {error}=await supabase.rpc("configure_utility_provider_route",{target_product_key:input.productKey,target_provider_adapter_key:input.providerKey,target_provider_product_code:input.productCode,target_priority:input.priority,target_status:input.state,target_fixed_fee:input.fee}); if(error) throw error; }, onSuccess:async()=>client.invalidateQueries({queryKey:["admin-utility-billing"]}) });
  const data=snapshot.data;
  return <>
    <PageHeader eyebrow="Customer services" title="Bills & everyday payments" description="Choose which services customers can pay for, connect approved service companies, and create offers—without technical setup screens." actions={<Button icon={RefreshCcw} variant="outline" onClick={()=>void snapshot.refetch()}>Refresh</Button>} />
    {snapshot.isLoading?<LoadingState label="Loading bill services"/>:snapshot.error?<ErrorState title="Bill services unavailable" message={snapshot.error.message} onRetry={()=>void snapshot.refetch()}/>:<section className="skima-grid skima-grid--compact"><MetricTile label="Service companies" value={data?.billers.length??0} icon={Building2}/><MetricTile label="Customer plans" value={data?.products.length??0} icon={Zap} tone="info"/><MetricTile label="Live connections" value={data?.routes.filter(item=>text(item,"status")==="active").length??0} icon={PlugZap}/><MetricTile label="Offers" value={data?.promotions.length??0} icon={BadgePercent}/></section>}
    <section className="sk-panel"><div className="sk-panel__header"><div><p className="admin-section-kicker">Guided setup</p><h2>Set up customer bill payments</h2><p>Complete the sections from left to right. Changes can remain hidden until you are ready to make them available.</p></div></div>
      <div className="utility-setup-tabs" role="tablist" aria-label="Bill payment setup">{steps.map(item=><button key={item.key} className={step===item.key?"is-active":""} type="button" onClick={()=>setStep(item.key)}><strong>{item.label}</strong><small>{item.detail}</small></button>)}</div>
      {step==="category"?<CategoryForm busy={save.isPending} error={save.error} onSave={(key,configuration)=>save.mutate({kind:"category",key,configuration})}/>:null}
      {step==="biller"?<BillerForm categories={data?.categories??[]} busy={save.isPending} error={save.error} onSave={(key,configuration)=>save.mutate({kind:"biller",key,configuration})}/>:null}
      {step==="product"?<ProductForm billers={data?.billers??[]} busy={save.isPending} error={save.error} onSave={(key,configuration)=>save.mutate({kind:"product",key,configuration})}/>:null}
      {step==="connection"?<ConnectionForm products={data?.products??[]} providers={data?.providers??[]} busy={connect.isPending} error={connect.error} onSave={input=>connect.mutate(input)}/>:null}
      {step==="promotion"?<PromotionForm busy={save.isPending} error={save.error} onSave={(key,configuration)=>save.mutate({kind:"promotion",key,configuration})}/>:null}
    </section>
    <section className="admin-notice"><strong>Payment protection</strong><p>Customer funds are only used after an approved connection confirms the payment. Failed payments must be returned automatically. New connections remain off until testing is complete.</p></section>
  </>;
}

type SaveProps={busy:boolean;error:Error|null;onSave(key:string,configuration:Record<string,unknown>):void};
function CategoryForm({busy,error,onSave}:SaveProps){const[name,setName]=useState("");const[description,setDescription]=useState("");const[state,setState]=useState("draft");return <Form title="Add a service type" description="Create a clear group customers will recognise, such as Cable TV or Education."><TextInput label="Service name" value={name} onChange={e=>setName(e.currentTarget.value)} placeholder="Cable TV"/><TextInput label="Short description" value={description} onChange={e=>setDescription(e.currentTarget.value)} placeholder="Pay television subscriptions"/><Visibility value={state} onChange={setState}/><Submit busy={busy} error={error} disabled={!name.trim()} onClick={()=>onSave(slug(name),{displayName:name.trim(),description:description.trim()||null,iconKey:"receipt",status:state})}/></Form>}
function BillerForm({categories,busy,error,onSave}:SaveProps&{categories:Row[]}){const[category,setCategory]=useState("");const[name,setName]=useState("");const[label,setLabel]=useState("Account number");const[hint,setHint]=useState("");const[state,setState]=useState("draft");return <Form title="Add a company" description="Add the electricity company, mobile network, television provider, or other company customers will pay."><SelectInput label="Service type" value={category} onChange={e=>setCategory(e.currentTarget.value)} options={options(categories,"key","display_name","Choose a service type")}/><TextInput label="Company name" value={name} onChange={e=>setName(e.currentTarget.value)} placeholder="Company name"/><TextInput label="Customer detail label" value={label} onChange={e=>setLabel(e.currentTarget.value)} placeholder="Meter number"/><TextInput label="Help text" value={hint} onChange={e=>setHint(e.currentTarget.value)} placeholder="Enter the number printed on your meter"/><Visibility value={state} onChange={setState}/><Submit busy={busy} error={error} disabled={!category||!name.trim()||!label.trim()} onClick={()=>onSave(`${category}.${slug(name)}`,{categoryKey:category,displayName:name.trim(),customerIdentifierLabel:label.trim(),customerIdentifierHint:hint.trim()||null,validationMode:"provider",status:state})}/></Form>}
function ProductForm({billers,busy,error,onSave}:SaveProps&{billers:Row[]}){const[biller,setBiller]=useState("");const[name,setName]=useState("");const[mode,setMode]=useState("customer");const[fixed,setFixed]=useState("");const[min,setMin]=useState("");const[max,setMax]=useState("");const[state,setState]=useState("draft");return <Form title="Add a payment plan" description="Define what customers can buy and the permitted amount range."><SelectInput label="Company" value={biller} onChange={e=>setBiller(e.currentTarget.value)} options={options(billers,"key","display_name","Choose a company")}/><TextInput label="Plan name" value={name} onChange={e=>setName(e.currentTarget.value)} placeholder="Prepaid electricity"/><SelectInput label="How is the amount chosen?" value={mode} onChange={e=>setMode(e.currentTarget.value)} options={[{label:"Customer enters an amount",value:"customer"},{label:"One fixed amount",value:"fixed"},{label:"Company supplies the price",value:"provider"}]}/>{mode==="fixed"?<TextInput label="Fixed amount (₦)" type="number" value={fixed} onChange={e=>setFixed(e.currentTarget.value)}/>:null}{mode==="customer"?<><TextInput label="Minimum amount (₦)" type="number" value={min} onChange={e=>setMin(e.currentTarget.value)}/><TextInput label="Maximum amount (₦)" type="number" value={max} onChange={e=>setMax(e.currentTarget.value)}/></>:null}<Visibility value={state} onChange={setState}/><Submit busy={busy} error={error} disabled={!biller||!name.trim()||(mode==="fixed"&&!positive(fixed))} onClick={()=>onSave(`${biller}.${slug(name)}`,{billerKey:biller,displayName:name.trim(),amountMode:mode,fixedAmount:numberOrNull(fixed),minimumAmount:numberOrNull(min),maximumAmount:numberOrNull(max),currencyCode:"NGN",status:state})}/></Form>}
function ConnectionForm({products,providers,busy,error,onSave}:{products:Row[];providers:Row[];busy:boolean;error:Error|null;onSave(input:{productKey:string;providerKey:string;productCode:string;priority:number;state:string;fee:number}):void}){const[product,setProduct]=useState("");const[provider,setProvider]=useState("");const[code,setCode]=useState("");const[fee,setFee]=useState("0");const[state,setState]=useState("inactive");return <Form title="Connect a payment plan" description="Choose an approved service connection and enter the product code supplied by that company.">{providers.length===0?<div className="admin-notice"><strong>No approved bill-payment connection yet</strong><p>Add and test a bill-payment provider under Integrations before making customer plans available.</p></div>:null}<SelectInput label="Payment plan" value={product} onChange={e=>setProduct(e.currentTarget.value)} options={options(products,"key","display_name","Choose a plan")}/><SelectInput label="Service connection" value={provider} onChange={e=>setProvider(e.currentTarget.value)} options={options(providers,"key","display_name","Choose a connection")}/><TextInput label="Company product code" value={code} onChange={e=>setCode(e.currentTarget.value)} placeholder="Code supplied by the service company"/><TextInput label="Customer fee (₦)" type="number" value={fee} onChange={e=>setFee(e.currentTarget.value)}/><SelectInput label="Customer availability" value={state} onChange={e=>setState(e.currentTarget.value)} options={[{label:"Keep unavailable",value:"inactive"},{label:"Make available",value:"active"}]}/><Submit busy={busy} error={error} disabled={!product||!provider||!code.trim()} onClick={()=>onSave({productKey:product,providerKey:provider,productCode:code.trim(),priority:100,state,fee:Number(fee)||0})}/></Form>}
function PromotionForm({busy,error,onSave}:SaveProps){const[name,setName]=useState("");const[kind,setKind]=useState("percentage");const[value,setValue]=useState("");const[cap,setCap]=useState("");const[min,setMin]=useState("");const[total,setTotal]=useState("");const[perCustomer,setPerCustomer]=useState("1");const[state,setState]=useState("draft");return <Form title="Create an offer" description="Set a discount and control how often it can be used."><TextInput label="Offer name" value={name} onChange={e=>setName(e.currentTarget.value)} placeholder="Welcome bill payment offer"/><SelectInput label="Discount type" value={kind} onChange={e=>setKind(e.currentTarget.value)} options={[{label:"Percentage",value:"percentage"},{label:"Fixed amount",value:"fixed"}]}/><TextInput label={kind==="percentage"?"Discount (%)":"Discount amount (₦)"} type="number" value={value} onChange={e=>setValue(e.currentTarget.value)}/>{kind==="percentage"?<TextInput label="Maximum discount (₦)" type="number" value={cap} onChange={e=>setCap(e.currentTarget.value)}/>:null}<TextInput label="Minimum customer spend (₦)" type="number" value={min} onChange={e=>setMin(e.currentTarget.value)}/><TextInput label="Total uses allowed" type="number" value={total} onChange={e=>setTotal(e.currentTarget.value)}/><TextInput label="Uses allowed per customer" type="number" value={perCustomer} onChange={e=>setPerCustomer(e.currentTarget.value)}/><Visibility value={state} onChange={setState}/><Submit busy={busy} error={error} disabled={!name.trim()||!positive(value)} onClick={()=>onSave(slug(name),{displayName:name.trim(),discountKind:kind,discountValue:Number(value),maximumDiscount:numberOrNull(cap),minimumSpend:numberOrNull(min),usageLimit:integerOrNull(total),perCustomerLimit:integerOrNull(perCustomer),status:state})}/></Form>}
function Form({title,description,children}:{title:string;description:string;children:React.ReactNode}){return <div className="utility-guided-form"><div><h3>{title}</h3><p>{description}</p></div><div className="skima-form">{children}</div></div>}
function Visibility({value,onChange}:{value:string;onChange(value:string):void}){return <SelectInput label="Visibility" value={value} onChange={e=>onChange(e.currentTarget.value)} options={[{label:"Save as draft",value:"draft"},{label:"Show to customers",value:"active"},{label:"Hide from customers",value:"inactive"}]}/>}
function Submit({busy,error,disabled,onClick}:{busy:boolean;error:Error|null;disabled:boolean;onClick():void}){return <>{error?<div className="admin-notice is-error" role="alert">{friendly(error)}</div>:null}<Button icon={Save} isLoading={busy} disabled={disabled} onClick={onClick}>Save changes</Button></>}
function options(rows:Row[],valueKey:string,labelKey:string,placeholder:string){return [{label:placeholder,value:""},...rows.map(row=>({label:text(row,labelKey)||"Unnamed",value:text(row,valueKey)})).filter(item=>item.value)]}
function text(row:Row,key:string){const value=row[key];return typeof value==="string"?value:""}
function slug(value:string){return value.trim().toLowerCase().replace(/[^a-z0-9]+/g,"-").replace(/^-|-$/g,"").slice(0,100)}
function positive(value:string){return Number.isFinite(Number(value))&&Number(value)>0}
function numberOrNull(value:string){return value.trim()===""?null:Number(value)}
function integerOrNull(value:string){return value.trim()===""?null:Math.max(1,Math.trunc(Number(value)))}
function friendly(error:Error){return error.message.replaceAll("target_","").replaceAll("_"," ")}
