import { Crosshair, Minus, Plus, RotateCcw } from "lucide-react";
import { useEffect, useMemo, useState, type MouseEvent } from "react";
import { Button, StatusBadge } from "@skima/ui";

type Coordinate = readonly [number, number];
const WIDTH = 800; const HEIGHT = 420; const TILE = 256;

export function AdminGeometryEditor(props: { value?: string; onChange?: (geojson: string) => void; point?: Coordinate | null; onPointChange?: (point: Coordinate) => void; mode: "polygon" | "point" }) {
  const initial = useMemo(() => readPolygons(props.value), [props.value]);
  const [polygons,setPolygons]=useState<Coordinate[][]>(initial.length?initial:[[]]); const [active,setActive]=useState(Math.max(initial.length-1,0)); const [center,setCenter]=useState<Coordinate>(()=>average(initial.flat())??props.point??[0,0]); const [zoom,setZoom]=useState(initial.length?12:2);
  useEffect(()=>{const next=initial.length?initial:[[]];setPolygons(next);setActive(Math.max(next.length-1,0));const nextCenter=average(initial.flat());if(nextCenter)setCenter(nextCenter);},[initial]);
  const tileTemplate=import.meta.env.VITE_MAP_TILE_URL_TEMPLATE as string|undefined; const attribution=(import.meta.env.VITE_MAP_ATTRIBUTION as string|undefined)??"Configured map provider";
  const layout=tiles(center,zoom,tileTemplate); const paths=polygons.map((polygon)=>polygonPath(polygon,center,zoom)); const pointPosition=props.point?screenPoint(props.point,center,zoom):null;
  const emit=(next:Coordinate[][])=>{setPolygons(next);const completed=next.filter((polygon)=>polygon.length>=3).map(closeRing);if(!props.onChange)return;if(completed.length===0)props.onChange("");else props.onChange(JSON.stringify(completed.length===1?{type:"Polygon",coordinates:[completed[0]]}:{type:"MultiPolygon",coordinates:completed.map((ring)=>[ring])},null,2));};
  const select=(event:MouseEvent<SVGSVGElement>)=>{const rect=event.currentTarget.getBoundingClientRect();const point=unproject(center,zoom,((event.clientX-rect.left)/rect.width)*WIDTH,((event.clientY-rect.top)/rect.height)*HEIGHT);if(props.mode==="point"){props.onPointChange?.(point);setCenter(point);return;}const next=polygons.map((polygon,index)=>index===active?[...polygon,point]:polygon);emit(next);};
  const undo=()=>emit(polygons.map((polygon,index)=>index===active?polygon.slice(0,-1):polygon)); const clear=()=>{setActive(0);emit([[]]);}; const addPolygon=()=>{const next=[...polygons,[]];setActive(next.length-1);emit(next);};
  return <section className="sk-panel"><div className="sk-panel__header"><div><h3>{props.mode==="polygon"?"Interactive boundary editor":"Select radius center"}</h3><p className="skima-muted">{props.mode==="polygon"?"Click the map to add vertices. Create another ring for a MultiPolygon.":"Click the map to set the approved center point."}</p></div><div className="skima-action-row"><Button size="sm" variant="outline" icon={Minus} onClick={()=>setZoom(Math.max(1,zoom-1))}>Zoom out</Button><Button size="sm" variant="outline" icon={Plus} onClick={()=>setZoom(Math.min(20,zoom+1))}>Zoom in</Button></div></div><svg role="application" aria-label={props.mode==="polygon"?"Interactive polygon boundary map":"Interactive radius center map"} onClick={select} viewBox={`0 0 ${WIDTH} ${HEIGHT}`} style={{width:"100%",minHeight:360,border:"1px solid #ccd7dc",borderRadius:16,background:"#eaf0f2",cursor:"crosshair"}}>{layout.map((tile)=><image key={`${tile.z}:${tile.x}:${tile.y}`} href={tile.url} x={tile.left} y={tile.top} width={TILE} height={TILE}/>) }{!tileTemplate?<><path d={`M0 ${HEIGHT/2}H${WIDTH} M${WIDTH/2} 0V${HEIGHT}`} stroke="#b7c5cb" strokeDasharray="6 6"/><text x="20" y="30" fill="#52666f">Configure VITE_MAP_TILE_URL_TEMPLATE for the provider basemap</text></>:null}{paths.map((path,index)=><path key={index} d={path} fill="#246bdb44" stroke={index===active?"#1457b8":"#50769e"} strokeWidth={index===active?3:2} fillRule="evenodd"/>)}{polygons.flatMap((polygon,polygonIndex)=>polygon.map((coordinate,index)=>{const [x,y]=screenPoint(coordinate,center,zoom);return <circle key={`${polygonIndex}:${index}`} cx={x} cy={y} r={polygonIndex===active?5:3} fill="#1457b8" stroke="white" strokeWidth="2"/>;}))}{pointPosition?<><circle cx={pointPosition[0]} cy={pointPosition[1]} r="10" fill="#1457b8" stroke="white" strokeWidth="4"/><path d={`M${pointPosition[0]-16} ${pointPosition[1]}H${pointPosition[0]+16} M${pointPosition[0]} ${pointPosition[1]-16}V${pointPosition[1]+16}`} stroke="#1457b8"/></>:null}</svg><div className="skima-action-row"><StatusBadge tone="info">{props.mode==="polygon"?`${polygons.reduce((sum,polygon)=>sum+polygon.length,0)} vertices · ${polygons.filter((polygon)=>polygon.length>=3).length} polygon(s)`:props.point?`${props.point[1].toFixed(6)}, ${props.point[0].toFixed(6)}`:"No center selected"}</StatusBadge>{props.mode==="polygon"?<><Button size="sm" variant="outline" icon={RotateCcw} onClick={undo}>Undo vertex</Button><Button size="sm" variant="outline" onClick={addPolygon}>New polygon</Button><Button size="sm" variant="destructive" onClick={clear}>Clear</Button></>:<Button size="sm" variant="outline" icon={Crosshair} onClick={()=>props.point&&setCenter(props.point)}>Recenter</Button>}</div><p className="skima-muted">Basemap: {attribution}. Geometry remains authoritative only after server preview and activation.</p></section>;
}

function readPolygons(value?:string):Coordinate[][]{if(!value?.trim())return[];try{const geometry=JSON.parse(value) as {type?:string;coordinates?:unknown};if(geometry.type==="Polygon"&&Array.isArray(geometry.coordinates))return [(geometry.coordinates[0] as Coordinate[]).slice(0,-1)];if(geometry.type==="MultiPolygon"&&Array.isArray(geometry.coordinates))return geometry.coordinates.map((polygon)=>((polygon as Coordinate[][])[0]??[]).slice(0,-1));}catch{return [];}return[];}
function closeRing(points:Coordinate[]):Coordinate[]{return [...points,points[0]];}
function average(points:Coordinate[]):Coordinate|null{if(!points.length)return null;return[points.reduce((sum,p)=>sum+p[0],0)/points.length,points.reduce((sum,p)=>sum+p[1],0)/points.length];}
function world(point:Coordinate,zoom:number):Coordinate{const scale=TILE*2**zoom;const sin=Math.sin(point[1]*Math.PI/180);return[(point[0]+180)/360*scale,(0.5-Math.log((1+sin)/(1-sin))/(4*Math.PI))*scale];}
function screenPoint(point:Coordinate,center:Coordinate,zoom:number):Coordinate{const p=world(point,zoom),c=world(center,zoom);return[WIDTH/2+p[0]-c[0],HEIGHT/2+p[1]-c[1]];}
function unproject(center:Coordinate,zoom:number,x:number,y:number):Coordinate{const scale=TILE*2**zoom,c=world(center,zoom),wx=c[0]+x-WIDTH/2,wy=c[1]+y-HEIGHT/2;const longitude=wx/scale*360-180;const n=Math.PI-2*Math.PI*wy/scale;return[Math.max(-180,Math.min(180,longitude)),Math.max(-85.051129,Math.min(85.051129,180/Math.PI*Math.atan(0.5*(Math.exp(n)-Math.exp(-n)))) )];}
function polygonPath(points:Coordinate[],center:Coordinate,zoom:number):string{return points.map((point,index)=>{const[x,y]=screenPoint(point,center,zoom);return`${index?"L":"M"}${x.toFixed(2)},${y.toFixed(2)}`;}).join(" ")+(points.length>=3?" Z":"");}
function tiles(center:Coordinate,zoom:number,template?:string){if(!template)return[];const c=world(center,zoom),minX=Math.floor((c[0]-WIDTH/2)/TILE),maxX=Math.floor((c[0]+WIDTH/2)/TILE),minY=Math.floor((c[1]-HEIGHT/2)/TILE),maxY=Math.floor((c[1]+HEIGHT/2)/TILE),count=2**zoom,result:{z:number;x:number;y:number;left:number;top:number;url:string}[]=[];for(let y=minY;y<=maxY;y++)for(let x=minX;x<=maxX;x++){if(y<0||y>=count)continue;const wrapped=((x%count)+count)%count;result.push({z:zoom,x:wrapped,y,left:x*TILE-(c[0]-WIDTH/2),top:y*TILE-(c[1]-HEIGHT/2),url:template.replace("{z}",String(zoom)).replace("{x}",String(wrapped)).replace("{y}",String(y))});}return result;}
