import * as Linking from "expo-linking";
import { router } from "expo-router";
import { useState } from "react";
import { ActivityIndicator, Pressable, StyleSheet, Text, TextInput } from "react-native";
import { useSession } from "../../src/native/session/SessionProvider";
import { colors, radii, spacing } from "../../src/native/theme/tokens";
import { Screen } from "../../src/native/ui/Screen";
export default function ForgotPassword() { const session = useSession(); const [email, setEmail] = useState(""); const [pending, setPending] = useState(false); const [message, setMessage] = useState<string | null>(null); const submit = async () => { setPending(true); setMessage(null); try { const { error } = await session.supabase.auth.resetPasswordForEmail(email.trim(), { redirectTo: Linking.createURL("reset-password") }); if (error) throw error; setMessage("If this email belongs to an account, your reset link is on its way."); } catch { setMessage("We couldn’t send the reset email. Check your connection and try again."); } finally { setPending(false); } }; return <Screen eyebrow="Account recovery" title="Reset your password" action={<Pressable onPress={() => router.back()}><Text style={styles.link}>Back</Text></Pressable>}><Text style={styles.copy}>Enter the email linked to your SKIMA account.</Text><TextInput style={styles.input} autoCapitalize="none" keyboardType="email-address" placeholder="Email address" placeholderTextColor={colors.muted} value={email} onChangeText={setEmail} /><Pressable disabled={pending || !email.trim()} style={styles.primary} onPress={() => void submit()}>{pending ? <ActivityIndicator color="white" /> : <Text style={styles.primaryText}>Send reset link</Text>}</Pressable>{message ? <Text style={styles.message}>{message}</Text> : null}</Screen>; }
const styles = StyleSheet.create({ link: { color: colors.brand, fontWeight: "800" }, copy: { color: colors.muted, lineHeight: 22 }, input: { minHeight: 56, borderWidth: 1, borderColor: colors.border, borderRadius: radii.md, backgroundColor: colors.surface, paddingHorizontal: spacing.md, color: colors.ink, fontSize: 16 }, primary: { minHeight: 56, alignItems: "center", justifyContent: "center", borderRadius: radii.md, backgroundColor: colors.brand }, primaryText: { color: "white", fontWeight: "900" }, message: { color: colors.brandDark, fontWeight: "700" } });
