import { router } from "expo-router";
import { CreditCard, ReceiptText, ShieldCheck } from "lucide-react-native";
import { ActivityIndicator, Pressable, StyleSheet, Text, View } from "react-native";
import { domainQueries } from "../api/domains";
import { displayReference, displayStatus, firstNumber, firstString, recordId } from "../api/records";
import { colors, radii, spacing } from "../theme/tokens";
import { Card } from "./Card";
import { Screen } from "./Screen";
export function TransactionsScreen() { const transactions = domainQueries.transactions(); const wallets = domainQueries.wallets(); const currency = firstString(wallets.data?.[0], ["currency_code", "currencyCode"]) ?? "NGN"; return <Screen eyebrow="Payment activity" title="Transactions" action={<Back />}>{transactions.isPending ? <ActivityIndicator color={colors.brand} /> : <>{(transactions.data ?? []).map((item, index) => <Card key={recordId(item) ?? String(index)}><View style={styles.row}><View style={styles.icon}><ReceiptText color={colors.brand} size={22} /></View><View style={{ flex: 1 }}><Text style={styles.title}>{displayReference(item) ?? "Wallet transaction"}</Text><Text style={styles.body}>{formatDate(firstString(item, ["created_at", "createdAt"]))} · {(displayStatus(item) ?? "recorded").replace(/[_-]/g, " ")}</Text><Text style={styles.meta}>{firstString(item, ["provider_reference", "providerReference"]) ?? "Reference pending"}</Text></View><Text style={styles.money}>{money(firstNumber(item, ["amount", "net_amount", "netAmount"]) ?? 0, firstString(item, ["currency_code", "currencyCode"]) ?? currency)}</Text></View></Card>)}{(transactions.data ?? []).length === 0 ? <Empty icon={ReceiptText} title="No transactions yet" body="Payments and wallet activity will appear here." /> : null}</>}</Screen>; }
export function PaymentProvidersScreen() { const providers = domainQueries.providers(); const payment = (providers.data ?? []).filter((item) => firstString(item, ["provider_kind", "providerKind"]) === "payment" && firstString(item, ["status"]) === "active"); return <Screen eyebrow="Payments" title="Payment methods" action={<Back />}>{providers.isPending ? <ActivityIndicator color={colors.brand} /> : <>{payment.map((item, index) => <Card key={recordId(item) ?? firstString(item, ["key"]) ?? String(index)}><View style={styles.row}><View style={styles.icon}><CreditCard color={colors.brand} size={23} /></View><View style={{ flex: 1 }}><Text style={styles.title}>{firstString(item, ["display_name", "displayName", "key"]) ?? "Payment method"}</Text><Text style={styles.body}>Choose this option when adding money or paying for a refill.</Text></View><ShieldCheck color={colors.success} size={23} /></View></Card>)}{payment.length === 0 ? <Empty icon={CreditCard} title="Payments are unavailable" body="Please try again later or contact SKIMA support." /> : null}</>}</Screen>; }
function Back() { return <Pressable onPress={() => router.back()}><Text style={styles.link}>Back</Text></Pressable>; }
function Empty({ icon: Icon, title, body }: { icon: typeof ReceiptText; title: string; body: string }) { return <View style={styles.empty}><View style={styles.emptyIcon}><Icon color={colors.brand} size={31} /></View><Text style={styles.emptyTitle}>{title}</Text><Text style={styles.body}>{body}</Text></View>; }
function money(value: number, currency: string) { try { return new Intl.NumberFormat(undefined, { style: "currency", currency }).format(value); } catch { return `${currency} ${value.toFixed(2)}`; } }
function formatDate(value: string | null) { if (!value) return "Date unavailable"; const date = new Date(value); return Number.isNaN(date.getTime()) ? value : date.toLocaleString(); }
const styles = StyleSheet.create({ row: { flexDirection: "row", alignItems: "center", gap: spacing.md }, icon: { width: 48, height: 48, borderRadius: 16, alignItems: "center", justifyContent: "center", backgroundColor: "#FFF0F1" }, title: { color: colors.ink, fontSize: 17, fontWeight: "900" }, body: { color: colors.muted, lineHeight: 20, textTransform: "capitalize" }, meta: { color: colors.muted, fontSize: 12, marginTop: 4 }, money: { color: colors.ink, fontSize: 16, fontWeight: "900" }, link: { color: colors.brand, fontWeight: "900" }, empty: { minHeight: 250, alignItems: "center", justifyContent: "center", gap: spacing.md, padding: spacing.xl }, emptyIcon: { width: 66, height: 66, borderRadius: 33, alignItems: "center", justifyContent: "center", backgroundColor: "#FFF0F1" }, emptyTitle: { color: colors.ink, fontSize: 21, fontWeight: "900" }, disclaimer: { color: colors.muted, lineHeight: 20 } });
