import { router } from "expo-router";
import { Plus, QrCode } from "lucide-react-native";
import { ActivityIndicator, Pressable, StyleSheet, Text, View } from "react-native";
import { domainQueries } from "../api/domains";
import { displayReference, displayStatus, displayTitle, firstNumber, firstString, recordId } from "../api/records";
import { colors, radii, spacing } from "../theme/tokens";
import { Screen } from "./Screen";
export function CylindersScreen() { const cylinders = domainQueries.cylinders(); return <Screen eyebrow="Verified assets" title="My cylinders" action={<Pressable onPress={() => router.push("/(customer)/cylinder/register")} style={styles.action}><Plus color="white" size={18} /><Text style={styles.actionText}>Register</Text></Pressable>}>{cylinders.isPending ? <ActivityIndicator color={colors.brand} /> : <>{(cylinders.data ?? []).map((item, index) => { const id = recordId(item); return <Pressable key={id ?? String(index)} disabled={!id} onPress={() => router.push(`/(customer)/cylinder/${id}` as never)} style={styles.asset}><View style={styles.cylinder}><QrCode color={colors.brand} size={33} /></View><View style={{ flex: 1, gap: 4 }}><Text style={styles.title}>{displayTitle(item)}</Text><Text style={styles.body}>{firstNumber(item, ["size_kg", "sizeKg"]) ?? "Configured"} kg · {displayReference(item) ?? firstString(item, ["cylinder_identifier", "cylinderIdentifier"])}</Text><View style={styles.row}><Text style={styles.status}>{(displayStatus(item) ?? "registered").replace(/[_-]/g, " ")}</Text><Text style={styles.meta}>{firstString(item, ["brand", "manufacturer"]) ?? "Brand not recorded"}</Text></View></View></Pressable>; })}{(cylinders.data ?? []).length === 0 ? <View style={styles.empty}><View style={styles.emptyIcon}><QrCode color={colors.brand} size={32} /></View><Text style={styles.emptyTitle}>Register your first cylinder</Text><Text style={styles.emptyBody}>A real cylinder record is required before requesting a refill. QR identity and inspection history remain backend-authoritative.</Text><Pressable onPress={() => router.push("/(customer)/cylinder/register")} style={styles.primary}><Text style={styles.actionText}>Register cylinder</Text></Pressable></View> : null}</>}</Screen>; }
const styles = StyleSheet.create({ action: { flexDirection: "row", alignItems: "center", gap: 6, paddingHorizontal: 15, paddingVertical: 10, borderRadius: radii.pill, backgroundColor: colors.brand }, actionText: { color: "white", fontWeight: "900" }, asset: { flexDirection: "row", alignItems: "center", gap: spacing.md, padding: spacing.lg, borderRadius: radii.lg, borderWidth: 1, borderColor: colors.border, backgroundColor: colors.surface }, cylinder: { width: 66, height: 82, alignItems: "center", justifyContent: "center", borderRadius: 28, backgroundColor: "#FFF0F1" }, title: { color: colors.ink, fontSize: 17, fontWeight: "900" }, body: { color: colors.muted }, row: { flexDirection: "row", gap: spacing.sm, alignItems: "center" }, status: { color: colors.brandDark, fontWeight: "800", textTransform: "capitalize" }, meta: { color: colors.muted, fontSize: 12 }, empty: { minHeight: 290, alignItems: "center", justifyContent: "center", gap: spacing.md, padding: spacing.xl }, emptyIcon: { width: 70, height: 70, borderRadius: 35, alignItems: "center", justifyContent: "center", backgroundColor: "#FFF0F1" }, emptyTitle: { color: colors.ink, fontSize: 21, fontWeight: "900" }, emptyBody: { maxWidth: 480, color: colors.muted, textAlign: "center", lineHeight: 21 }, primary: { minHeight: 52, alignItems: "center", justifyContent: "center", paddingHorizontal: spacing.xl, borderRadius: radii.md, backgroundColor: colors.brand } });
