import { useState } from "react";
import { ActivityIndicator, Pressable, StyleSheet, Text, TextInput, View } from "react-native";
import { domainQueries } from "../api/domains";
import { useGatewayMutation } from "../api/gateway";
import { ActionResponseSchema, displayTitle, recordId } from "../api/records";
import { readOperationalLocation } from "../device/location";
import { colors, radii, spacing } from "../theme/tokens";
import { idempotencyKey } from "../utilities/idempotency";
import { Screen } from "./Screen";
export function LocationsScreen() { const locations = domainQueries.locations(); const [label, setLabel] = useState(""); const [address, setAddress] = useState(""); const [notice, setNotice] = useState<string | null>(null); const mutation = useGatewayMutation({ path: "/lpg/locations", schema: ActionResponseSchema, invalidate: [["locations"]] }); const save = async () => { if (!label.trim() || !address.trim()) { setNotice("Enter a label and formatted address."); return; } try { const point = await readOperationalLocation(); await mutation.mutateAsync({ label: label.trim(), formattedAddress: address.trim(), ...point, idempotencyKey: idempotencyKey("create-location", label.trim()) }); setLabel(""); setAddress(""); setNotice("Delivery location saved."); } catch (cause) { setNotice(cause instanceof Error ? cause.message : "Location could not be saved."); } }; return <Screen eyebrow="Delivery" title="Addresses"><View style={styles.list}>{(locations.data ?? []).map((item, index) => <View key={recordId(item) ?? String(index)} style={styles.item}><Text style={styles.itemTitle}>{displayTitle(item)}</Text></View>)}</View><View style={styles.form}><Text style={styles.formTitle}>Add current location</Text><TextInput value={label} onChangeText={setLabel} placeholder="Label, e.g. Home" placeholderTextColor={colors.muted} style={styles.input} /><TextInput value={address} onChangeText={setAddress} placeholder="Formatted address" placeholderTextColor={colors.muted} style={styles.input} /><Pressable disabled={mutation.isPending} onPress={() => void save()} style={styles.primary}>{mutation.isPending ? <ActivityIndicator color="white" /> : <Text style={styles.primaryText}>Use device location and save</Text>}</Pressable>{notice ? <Text style={styles.notice}>{notice}</Text> : null}</View></Screen>; }
const styles = StyleSheet.create({ list: { gap: spacing.sm }, item: { padding: spacing.lg, borderRadius: radii.md, borderWidth: 1, borderColor: colors.border, backgroundColor: colors.surface }, itemTitle: { color: colors.ink, fontWeight: "800" }, form: { maxWidth: 620, gap: spacing.md, padding: spacing.lg, borderRadius: radii.lg, backgroundColor: colors.surface, borderWidth: 1, borderColor: colors.border }, formTitle: { color: colors.ink, fontSize: 19, fontWeight: "900" }, input: { minHeight: 54, borderRadius: radii.md, borderWidth: 1, borderColor: colors.border, paddingHorizontal: spacing.md, color: colors.ink }, primary: { minHeight: 54, alignItems: "center", justifyContent: "center", borderRadius: radii.md, backgroundColor: colors.brand }, primaryText: { color: "white", fontWeight: "900" }, notice: { color: colors.success, fontWeight: "700" } });
