import * as Print from "expo-print";
import { router, useLocalSearchParams } from "expo-router";
import * as Sharing from "expo-sharing";
import { ReceiptText, ShieldCheck } from "lucide-react-native";
import { ActivityIndicator, Pressable, StyleSheet, Text, View } from "react-native";
import { domainQueries } from "../api/domains";
import { displayReference, displayStatus, firstNumber, firstString, recordId } from "../api/records";
import { colors, radii, spacing } from "../theme/tokens";
import { Card } from "./Card";
import { Screen } from "./Screen";
export function ReceiptScreen() { const { id } = useLocalSearchParams<{ id?: string }>(); const orders = domainQueries.orders(); const order = orders.data?.find((item) => recordId(item) === id || displayReference(item) === id); const currency = firstString(order, ["currency_code", "currencyCode"]) ?? "NGN"; const total = firstNumber(order, ["total_amount", "totalAmount", "quoted_total", "quotedTotal"]); const status = order ? displayStatus(order) ?? "recorded" : ""; const share = async () => { if (!order) return; const reference = displayReference(order) ?? recordId(order) ?? "SKIMA LPG order"; const file = await Print.printToFileAsync({ html: `<html><body style="font-family:Arial;padding:48px;color:#17221b"><h1 style="color:#d7192d">SKIMA LPG</h1><h2>Payment receipt</h2><hr/><p><strong>Order:</strong> ${escapeHtml(reference)}</p><p><strong>Status:</strong> ${escapeHtml(status.replace(/[_-]/g, " "))}</p><p><strong>Total:</strong> ${escapeHtml(money(total, currency))}</p><p><strong>Payment status:</strong> ${escapeHtml((firstString(order, ["payment_status", "paymentStatus"]) ?? "confirmed").replace(/[_-]/g, " "))}</p><p><strong>Date:</strong> ${escapeHtml(formatDate(firstString(order, ["updated_at", "updatedAt", "created_at", "createdAt"])))}</p><p style="margin-top:40px;color:#66736b">Thank you for using SKIMA.</p></body></html>` }); if (await Sharing.isAvailableAsync()) await Sharing.shareAsync(file.uri, { mimeType: "application/pdf", dialogTitle: "Share SKIMA LPG receipt" }); }; return <Screen eyebrow="Payment" title="Receipt" action={<Pressable onPress={() => router.back()}><Text style={styles.back}>Back</Text></Pressable>}>{orders.isPending ? <ActivityIndicator color={colors.brand} /> : !order ? <Text style={styles.error}>A receipt is not available for this order yet.</Text> : <><View style={styles.hero}><ReceiptText color="white" size={34} /><View><Text style={styles.heroLabel}>ORDER RECEIPT</Text><Text style={styles.heroValue}>{money(total, currency)}</Text></View></View><Card><Field label="Order reference" value={displayReference(order) ?? "Unavailable"} /><Field label="Order status" value={status.replace(/[_-]/g, " ")} /><Field label="Payment status" value={(firstString(order, ["payment_status", "paymentStatus"]) ?? "Confirmed").replace(/[_-]/g, " ")} /><Field label="Date" value={formatDate(firstString(order, ["updated_at", "updatedAt", "created_at", "createdAt"]))} /></Card><View style={styles.verified}><ShieldCheck color={colors.success} size={21} /><Text style={styles.body}>This receipt reflects the latest confirmed payment for your order.</Text></View><Pressable onPress={() => void share()} style={styles.primary}><Text style={styles.primaryText}>Download or share PDF receipt</Text></Pressable></>}</Screen>; }
function Field({ label, value }: { label: string; value: string }) { return <View style={{ gap: 4 }}><Text style={styles.label}>{label}</Text><Text style={styles.value}>{value}</Text></View>; }
function money(value: number | null, currency: string) { if (value === null) return "Amount unavailable"; try { return new Intl.NumberFormat(undefined, { style: "currency", currency }).format(value); } catch { return `${currency} ${value.toFixed(2)}`; } }
function formatDate(value: string | null) { if (!value) return "Date unavailable"; const date = new Date(value); return Number.isNaN(date.getTime()) ? value : date.toLocaleString(); }
function escapeHtml(value: string) { return value.replace(/[&<>"']/g, (character) => ({ "&": "&amp;", "<": "&lt;", ">": "&gt;", '"': "&quot;", "'": "&#39;" })[character] ?? character); }
const styles = StyleSheet.create({ back: { color: colors.brand, fontWeight: "900" }, hero: { flexDirection: "row", alignItems: "center", gap: spacing.lg, padding: spacing.xl, borderRadius: radii.lg, backgroundColor: colors.brand }, heroLabel: { color: "#FFDDE1", fontSize: 11, fontWeight: "900" }, heroValue: { color: "white", fontSize: 32, fontWeight: "900", marginTop: 4 }, label: { color: colors.muted, fontSize: 11, fontWeight: "800", textTransform: "uppercase" }, value: { color: colors.ink, fontSize: 16, fontWeight: "800", textTransform: "capitalize" }, verified: { flexDirection: "row", gap: spacing.sm, padding: spacing.md, borderRadius: radii.md, backgroundColor: "#E9F7EE" }, body: { flex: 1, color: colors.muted, lineHeight: 20 }, primary: { minHeight: 56, alignItems: "center", justifyContent: "center", borderRadius: radii.md, backgroundColor: colors.brand }, primaryText: { color: "white", fontWeight: "900" }, error: { color: colors.danger } });
