import { router } from "expo-router";
import { Bell, ChevronRight, CircleHelp, FileCheck2 } from "lucide-react-native";
import { Pressable, StyleSheet, Text, View } from "react-native";
import { useSession } from "../session/SessionProvider";
import { colors, spacing } from "../theme/tokens";
import { Card } from "./Card";
import { Screen } from "./Screen";
const menus = {
  driver: [{ label: "Driver profile", href: "/(driver)/profile" }, { label: "Service zones", href: "/(driver)/service-zone" }, { label: "Application and approval", href: "/(driver)/application" }, { label: "Vehicles", href: "/(driver)/vehicles" }, { label: "Documents", href: "/(driver)/documents" }],
  station: [{ label: "Branch profile", href: "/(station)/profile" }, { label: "Inventory and capacity", href: "/(station)/inventory" }, { label: "Station reports", href: "/(station)/reports" }, { label: "Station settings and pricing", href: "/(station)/settings" }, { label: "Staff and permissions", href: "/(station)/staff" }, { label: "Roles and permission keys", href: "/(station)/roles" }, { label: "Application and approval", href: "/(station)/application" }, { label: "Documents", href: "/(station)/documents" }],
  customer: [{ label: "Apply to drive", href: "/(customer)/driver-application" }, { label: "Apply as a station", href: "/(customer)/station-application" }, { label: "Delivery addresses", href: "/(customer)/locations" }, { label: "Stations near you", href: "/(customer)/stations" }, { label: "Transactions", href: "/(customer)/transactions" }, { label: "Payment providers", href: "/(customer)/payment-methods" }],
} as const;
export function WorkspaceAccount({ workspace }: { workspace: string }) { const session = useSession(); const group = workspace.toLowerCase() as keyof typeof menus; const operational = menus[group] ?? menus.customer; return <Screen eyebrow={workspace} title="Account"><Card><Text style={styles.name}>{session.context?.profile?.display_name ?? "SKIMA member"}</Text><Text style={styles.meta}>{session.context?.user.email ?? ""}</Text><Text style={styles.meta}>{session.context?.roles.map((role) => role.displayName ?? role.key).filter(Boolean).join(" · ") || "Customer"}</Text></Card><View style={styles.menu}><Menu icon={Bell} label="Notifications" onPress={() => router.push(`/${`(${group})`}/notifications` as never)} />{operational.map((item) => <Menu key={item.label} icon={FileCheck2} label={item.label} onPress={() => router.push(item.href as never)} />)}<Menu icon={CircleHelp} label="Support and safety" onPress={() => router.push(`/${`(${group})`}/support` as never)} /></View><Pressable onPress={() => void session.signOut()}><Text style={styles.out}>Sign out</Text></Pressable></Screen>; }
function Menu({ icon: Icon, label, onPress }: { icon: typeof Bell; label: string; onPress?: () => void }) { return <Pressable onPress={onPress} style={styles.menuRow}><View style={styles.menuIcon}><Icon color={colors.brand} size={20} /></View><Text style={styles.menuText}>{label}</Text><ChevronRight color={colors.muted} size={18} /></Pressable>; }
const styles = StyleSheet.create({ name: { fontSize: 20, fontWeight: "800", color: colors.ink }, meta: { color: colors.muted }, menu: { borderRadius: 20, overflow: "hidden", borderWidth: 1, borderColor: colors.border, backgroundColor: colors.surface }, menuRow: { minHeight: 66, flexDirection: "row", alignItems: "center", gap: spacing.md, paddingHorizontal: spacing.md, borderBottomWidth: 1, borderBottomColor: colors.border }, menuIcon: { width: 38, height: 38, borderRadius: 19, alignItems: "center", justifyContent: "center", backgroundColor: "#FFF0F1" }, menuText: { flex: 1, color: colors.ink, fontWeight: "800" }, out: { color: colors.danger, fontWeight: "800", paddingVertical: spacing.md } });
